### ISSUE TITLE
[Suggestion] Nightmare plugin

### ISSUE THREAD

**Issue by AverageHumanoid** [xKylee/plugins-source#53]
- Countdown timer to when parasites burst out after being impregnated (also show for teammates)
- Countdown timer to when nightmare will dash after teleporting
- Highlight path of where nightmare will dash

**Comment by AverageHumanoid** [comment]
Countdown timer could be next to player similar to imbued heart https://imgur.com/a/cUUNmLL

**Comment by big213** [comment]
I was able to easily implement the tick timer for when the parasite bursts out using chat messages, but obviously chat messages are not available for others. Perhaps there is a way to identify which other teammates have been impregnated with the parasite based on projectiles, but I personally think that is not too useful, as they should be monitoring themselves.

**Comment by AverageHumanoid** [comment]
@big213 the reason I mentioned also showing countdown for teammates is in the case that some teammates get assigned to dwh while you are assigned to dclaw the parasites ASAP

**Comment by AverageHumanoid** [comment]
Another feature mentioned on Discord is adding guitar hero mode similar to the Cerberus plugin.

**Comment by big213** [comment]
Ah yeah, fair point. I'll see what can be done for marking all of the players with the parasites.

For the guitar hero, there's the minimalist guitar hero (i.e. mark the appropriate prayer to select after the animation occurs), or the camping melee prayer guitar hero (i.e. switch to melee prayer after the attack is over, since the melee attack registers 1 tick (or 2?) faster than the other attacks. Which one do you think would be most useful?

**Comment by AverageHumanoid** [comment]
The plugin currently shows what to pray as the animation occurs so I think guitar hero should behave similarly. Players can still choose to camp melee prayer the majority of the time and switch to mage/range only on the tick those attacks happen which should be easier with guitar hero mode.
